version: '3.8'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=carmgmt_db
      - DATABASE_USER=carmgmt_user
      - DATABASE_PASSWORD=suha1966
      - DATABASE_HOST=db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: carmgmt_db
      POSTGRES_USER: carmgmt_user
      POSTGRES_PASSWORD: suha1966
    ports:
      - "5432:5432"
