# Generated by Django 5.0.4 on 2024-04-06 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0004_alter_car_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='carBrand',
        ),
    ]
