# Generated by Django 5.0.3 on 2024-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0005_rename_name_car_carbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='purchasedFrom',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
