# Generated by Django 5.0.3 on 2024-04-07 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0007_car_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='car',
            name='profit',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='car',
            name='salesman',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='soldDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='soldTo',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='totalSpent',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
