# Generated by Django 5.0.3 on 2024-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0008_car_notes_car_profit_car_salesman_car_solddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
